services:
  admin-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: admin-app
    ports:
      - "5000:3000"
    env_file:
      - .env
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
