services:
  ekoru-admin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru-admin
    ports:
      - "3100:3000"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
